// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
type SupabaseLike = ReturnType<typeof createClient> & {
  __shim?: boolean;
};

function createShim(): SupabaseLike {
  const noop = (..._args: any[]) => { /* no-op */ };
  const promiseNull = async () => null as any;
  const unsubscribe = () => { /* no-op */ };
  return {
    __shim: true,
    from: () => ({ select: promiseNull } as any),
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      onAuthStateChange: (_cb: any) => ({ data: { subscription: { unsubscribe } } }),
      signInWithPassword: promiseNull,
      signOut: promiseNull,
    } as any,
  } as any;
}

export const supabase: SupabaseLike = (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY)
  ? createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY)
  : createShim();